server:
  port: 7002

spring:
  application:
    #集群情况下，请保证application.name 相同，否则不可用（在eureka控制台unavailable-replicas中可以看到不可用的副本节点）
    name: clusterEureka

#双集群配置
eureka:
  instance:
    #    eureka服务器的实例名称
    hostname: eureka7002
  client:
    #    false表示不向注册中心注册自己
    register-with-eureka: false
    #    false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001:7001/eureka/
