server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh             # 路由的id，没有固定的规则但要求统一，建议配合服务名
          uri: http://localhost:8001    # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      # 断言，路径相对应的进行路由

#        - id: payment_routh2             # 路由的id，没有固定的规则但要求统一，建议配合服务名
#            uri: http://localhost:8001    # 匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/lb/**      # 断言，路径相对应的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      fetch-registry: true
      # true将服务注册到eureka
      register-with-eureka: true
      #      集群Eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
#      单机版Eureka
#      defaultZone: http://localhost:7001/eureka


