server:
  port: 7001

#双集群配置
eureka:
  instance:
    #    eureka服务器的实例名称
    hostname: eurek7001.com
  client:
    #    false表示不向注册中心注册自己
    register-with-eureka: false
    #    false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      deaultZone: http://eurek7002.com:7002/eureka/