server:
  port: 80

#spring:
#  application:
#    name: cloud-order-service

eureka:
  client:
    #    禁止自己当服务注册
    register-with-eureka: false
    # true将服务注册到eureka
    #    fetch-registry: true
    service-url:
      #      集群Eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
#      单机版Eureka
#      defaultZone: http://localhost:7001/eureka