server:
  port: 80

#spring:
#  application:
#    name: cloud-order-service

eureka:
  client:
    #    禁止自己当服务注册
    register-with-eureka: false
    # true将服务注册到eureka
    #    fetch-registry: true
    service-url:
      #      集群Eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
#      单机版Eureka
#      defaultZone: http://localhost:7001/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #  建立连接所需要的时间
  ReadTimeout: 5000
  #  建立连接后服务端响应的时间
  ConnectTimeout: 5000

logging:
  level:
    #    feign日志以什么级别监控哪个接口
    com.xlj.springcloud.service.PaymentFeignService: debug

